### PR TITLE
Import CMake target as an INTERFACE instead of a SHARED library

### PR DESCRIPTION
**Pull request by avaucher**
Under Windows, importing TBB as a CMake target with 
`target_link_libraries(executable tbb)`
does not work (See also #8 ).
The problem, if I understand it correctly, is that an imported shared target can refer to only one file, which poses a problem with `IMPORTED_LOCATION` when there are several dll files, as is the case for the debug version or when one has several components.

With this PR, tbb is imported as an INTERFACE library instead, with all dependencies set correctly.
This PR solves #8.

### CODE REVIEW

**Comment by justusc** [comment]
You are correct about imported libraries only allowing a single target. Unfortunately interface libraries don't allow the library to be exported either. 

The correct solution is to import each library individually and link them to a single interface like library target.  This is what it did at one point.

I will take a look at this in more detail.

**Comment by avaucher** [comment]
Yes, you are correct, I saw that the tests didn't pass just before your comment.
I was a bit curious why this doesn't work so I added a few commands in FindTBB.cmake to export the target; the tests now pass but I am not sure how much sense this makes :-/.

**Comment by avaucher** [comment]
Ok, now it appears to be working :)

**Comment by justusc** [comment]
I will review your changes in more detail later tonight before merging the change. It looks like you are on the right path.

**Pull request closed without merging**
