### PR TITLE
Needed to set NO_SONAME for Linux to link.

### PR DESCRIPTION
**Pull request by abergmeier-dsfishlabs**

### CODE REVIEW

**Comment by justusc** [comment]
I have tested and use this find module on Linux platform on a daily basis. I assure you this change is not necessary.

To use TBB in your application on linux, you need to install the dev package (on Ubuntu it is `libtbb-dev`), which includes the header files and creates a symbolic link for the library to a .so file name. Also, the header files are not installed unless you have installed the dev package, which would cause this find module to fail.

There maybe use cases where TBB is needed as a dependency only, in which case the dev package would not be strictly necessary. However, for such a use case, FindTBB.cmake would need to be modified so that it did not fail when the header files are not found. Unfortunately such a change would make it impossible to check the version of TBB.

**Comment by abergmeier-dsfishlabs** [comment]
> To use TBB in your application on linux, you need to install the dev package (on Ubuntu it is libtbb-dev), which includes the header files and creates a symbolic link for the library to a .so file name.

We do not use tbb from a package but the binary distribution. And then `FindTBB` fails.

**Comment by justusc** [comment]
> We do not use tbb from a package but the binary distribution. And then FindTBB fails.

Are you referring to the TBB binary packages from the TBB web page?

**Comment by abergmeier-dsfishlabs** [comment]
> Are you referring to the TBB binary packages from the TBB web page?

Yes exactly.

**Comment by abergmeier-dsfishlabs** [comment]
Ouch. Just noticed that just this change alone does not make it work.
I think I will now rather try to build TBB with CMake. Seems to be the easier route.

**Comment by justusc** [comment]
I am looking at the package right now and it definitely includes the .so files. I suspect that CMake is selecting the wrong library file for some reason. Perhaps due to a configuration variable you have set in your project. If you can provide a minimal failing example and you system details (compiler, os, and version numbers), I would be happy to help you resolve the issue.

**Comment by justusc** [comment]
One thing you can try is to run the test.sh script included in this project. It will allow you to verify that the installed TBB is working. I verified the find module against the binary package a while ago, but things can change.

**Comment by abergmeier-dsfishlabs** [comment]
Thanks for your effort.
Due to Wenzels great work I now have TBB statically linked on Linux. Will probably switch the other platforms, too.

**Pull request closed without merging**
